// Code generated by github.com/13k/geyser/apigen. DO NOT EDIT.
// API interface: IDOTA2AutomatedTourney.

package dota2

import (
	"github.com/13k/geyser"
	"net/http"
)

// SchemaDOTA2AutomatedTourney stores the SchemaInterfaces for interface IDOTA2AutomatedTourney.
var SchemaDOTA2AutomatedTourney = geyser.MustNewSchemaInterfaces(
	&geyser.SchemaInterface{
		Methods: geyser.MustNewSchemaMethods(
			&geyser.SchemaMethod{
				HTTPMethod:   http.MethodGet,
				Name:         "GetParticipationDetails",
				Params:       geyser.NewSchemaMethodParams(),
				Undocumented: true,
				Version:      1,
			},
			&geyser.SchemaMethod{
				HTTPMethod:   http.MethodGet,
				Name:         "GetPlayerHistory",
				Params:       geyser.NewSchemaMethodParams(),
				Undocumented: true,
				Version:      1,
			},
			&geyser.SchemaMethod{
				HTTPMethod:   http.MethodGet,
				Name:         "GetTournamentDetails",
				Params:       geyser.NewSchemaMethodParams(),
				Undocumented: true,
				Version:      1,
			},
		),
		Name:         "IDOTA2AutomatedTourney",
		Undocumented: true,
	},
)

// DOTA2AutomatedTourney represents interface IDOTA2AutomatedTourney.
//
// This is an undocumented interface.
type DOTA2AutomatedTourney struct {
	Client    *Client
	Interface *geyser.SchemaInterface
}

// NewDOTA2AutomatedTourney creates a new DOTA2AutomatedTourney interface.
func NewDOTA2AutomatedTourney(c *Client) (*DOTA2AutomatedTourney, error) {
	si, err := SchemaDOTA2AutomatedTourney.Get(geyser.SchemaInterfaceKey{Name: "IDOTA2AutomatedTourney"})

	if err != nil {
		return nil, err
	}

	s := &DOTA2AutomatedTourney{
		Client:    c,
		Interface: si,
	}

	return s, nil
}

// DOTA2AutomatedTourney creates a new DOTA2AutomatedTourney interface.
func (c *Client) DOTA2AutomatedTourney() (*DOTA2AutomatedTourney, error) {
	return NewDOTA2AutomatedTourney(c)
}

/*
GetParticipationDetails creates a Request for interface method GetParticipationDetails.

This is an undocumented method.
*/
func (i *DOTA2AutomatedTourney) GetParticipationDetails() (*geyser.Request, error) {
	sm, err := i.Interface.Methods.Get(geyser.SchemaMethodKey{
		Name:    "GetParticipationDetails",
		Version: 1,
	})

	if err != nil {
		return nil, err
	}

	req := &geyser.Request{
		Client:    i.Client,
		Interface: i.Interface,
		Method:    sm,
		Result:    &DOTA2AutomatedTourneyGetParticipationDetails{},
	}

	return req, nil
}

/*
GetPlayerHistory creates a Request for interface method GetPlayerHistory.

This is an undocumented method.
*/
func (i *DOTA2AutomatedTourney) GetPlayerHistory() (*geyser.Request, error) {
	sm, err := i.Interface.Methods.Get(geyser.SchemaMethodKey{
		Name:    "GetPlayerHistory",
		Version: 1,
	})

	if err != nil {
		return nil, err
	}

	req := &geyser.Request{
		Client:    i.Client,
		Interface: i.Interface,
		Method:    sm,
		Result:    &DOTA2AutomatedTourneyGetPlayerHistory{},
	}

	return req, nil
}

/*
GetTournamentDetails creates a Request for interface method GetTournamentDetails.

This is an undocumented method.
*/
func (i *DOTA2AutomatedTourney) GetTournamentDetails() (*geyser.Request, error) {
	sm, err := i.Interface.Methods.Get(geyser.SchemaMethodKey{
		Name:    "GetTournamentDetails",
		Version: 1,
	})

	if err != nil {
		return nil, err
	}

	req := &geyser.Request{
		Client:    i.Client,
		Interface: i.Interface,
		Method:    sm,
		Result:    &DOTA2AutomatedTourneyGetTournamentDetails{},
	}

	return req, nil
}
