// Code generated by github.com/13k/geyser/apigen. DO NOT EDIT.
// API interface: IDOTA2StreamSystem.

package dota2

import (
	"github.com/13k/geyser"
	"net/http"
)

// SchemaDOTA2StreamSystem stores the SchemaInterfaces for interface IDOTA2StreamSystem.
var SchemaDOTA2StreamSystem = geyser.MustNewSchemaInterfaces(
	&geyser.SchemaInterface{
		Methods: geyser.MustNewSchemaMethods(
			&geyser.SchemaMethod{
				HTTPMethod:   http.MethodGet,
				Name:         "GetBroadcasterInfo",
				Params:       geyser.NewSchemaMethodParams(),
				Undocumented: true,
				Version:      1,
			},
		),
		Name:         "IDOTA2StreamSystem",
		Undocumented: true,
	},
)

// DOTA2StreamSystem represents interface IDOTA2StreamSystem.
//
// This is an undocumented interface.
type DOTA2StreamSystem struct {
	Client    *Client
	Interface *geyser.SchemaInterface
}

// NewDOTA2StreamSystem creates a new DOTA2StreamSystem interface.
func NewDOTA2StreamSystem(c *Client) (*DOTA2StreamSystem, error) {
	si, err := SchemaDOTA2StreamSystem.Get(geyser.SchemaInterfaceKey{Name: "IDOTA2StreamSystem"})

	if err != nil {
		return nil, err
	}

	s := &DOTA2StreamSystem{
		Client:    c,
		Interface: si,
	}

	return s, nil
}

// DOTA2StreamSystem creates a new DOTA2StreamSystem interface.
func (c *Client) DOTA2StreamSystem() (*DOTA2StreamSystem, error) {
	return NewDOTA2StreamSystem(c)
}

/*
GetBroadcasterInfo creates a Request for interface method GetBroadcasterInfo.

This is an undocumented method.
*/
func (i *DOTA2StreamSystem) GetBroadcasterInfo() (*geyser.Request, error) {
	sm, err := i.Interface.Methods.Get(geyser.SchemaMethodKey{
		Name:    "GetBroadcasterInfo",
		Version: 1,
	})

	if err != nil {
		return nil, err
	}

	req := &geyser.Request{
		Client:    i.Client,
		Interface: i.Interface,
		Method:    sm,
		Result:    &DOTA2StreamSystemGetBroadcasterInfo{},
	}

	return req, nil
}
