// Code generated by geyser. DO NOT EDIT.

package dota2_test

import (
	"github.com/13k/geyser"
	"github.com/13k/geyser/dota2"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
)

func TestNewIDOTA2Events(t *testing.T) {
	client := &dota2.Client{}
	iface, err := dota2.NewIDOTA2Events(client)

	require.NoError(t, err)
	require.NotNil(t, iface)

	assert.Same(t, client, iface.Client)
	assert.NotNil(t, iface.Interface)
}

func TestIDOTA2Events_GetArcanaVotes(t *testing.T) {
	var iface *dota2.IDOTA2Events
	var err error
	var req *geyser.Request

	client := &dota2.Client{}

	iface, err = dota2.NewIDOTA2Events(client)

	require.NoError(t, err)
	require.NotNil(t, iface)

	req, err = iface.GetArcanaVotes()

	require.NoError(t, err)
	require.NotNil(t, req)

	assert.Same(t, client, req.Client)
	assert.Same(t, iface.Interface, req.Interface)

	if assert.NotNil(t, req.Method) {
		assert.Equal(t, "GetArcanaVotes", req.Method.Name)
		assert.Equal(t, 1, req.Method.Version)
	}
}

func TestIDOTA2Events_GetCurrentTriviaQuestions(t *testing.T) {
	var iface *dota2.IDOTA2Events
	var err error
	var req *geyser.Request

	client := &dota2.Client{}

	iface, err = dota2.NewIDOTA2Events(client)

	require.NoError(t, err)
	require.NotNil(t, iface)

	req, err = iface.GetCurrentTriviaQuestions()

	require.NoError(t, err)
	require.NotNil(t, req)

	assert.Same(t, client, req.Client)
	assert.Same(t, iface.Interface, req.Interface)

	if assert.NotNil(t, req.Method) {
		assert.Equal(t, "GetCurrentTriviaQuestions", req.Method.Name)
		assert.Equal(t, 1, req.Method.Version)
	}
}

func TestIDOTA2Events_GetMutations(t *testing.T) {
	var iface *dota2.IDOTA2Events
	var err error
	var req *geyser.Request

	client := &dota2.Client{}

	iface, err = dota2.NewIDOTA2Events(client)

	require.NoError(t, err)
	require.NotNil(t, iface)

	req, err = iface.GetMutations()

	require.NoError(t, err)
	require.NotNil(t, req)

	assert.Same(t, client, req.Client)
	assert.Same(t, iface.Interface, req.Interface)

	if assert.NotNil(t, req.Method) {
		assert.Equal(t, "GetMutations", req.Method.Name)
		assert.Equal(t, 1, req.Method.Version)
	}
}

func TestIDOTA2Events_GetTriviaQuestionAnswersSummary(t *testing.T) {
	var iface *dota2.IDOTA2Events
	var err error
	var req *geyser.Request

	client := &dota2.Client{}

	iface, err = dota2.NewIDOTA2Events(client)

	require.NoError(t, err)
	require.NotNil(t, iface)

	req, err = iface.GetTriviaQuestionAnswersSummary()

	require.NoError(t, err)
	require.NotNil(t, req)

	assert.Same(t, client, req.Client)
	assert.Same(t, iface.Interface, req.Interface)

	if assert.NotNil(t, req.Method) {
		assert.Equal(t, "GetTriviaQuestionAnswersSummary", req.Method.Name)
		assert.Equal(t, 1, req.Method.Version)
	}
}
