language: go
cache:
  directories:
    - $GOPATH/pkg/mod
addons:
  apt:
    packages:
      - libudev-dev
go:
  - 1.13.x
  - 1.14.x
env:
  global:
    - GO111MODULE=on
    - GOLANGCI_VERSION=v1.25.1
before_script:
  - curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b "$(go env GOPATH)/bin" "$GOLANGCI_VERSION"
script:
  - go test -v -race -covermode atomic -coverprofile=coverage.txt ./...
  - bash <(curl -s https://codecov.io/bash)
  - golangci-lint run
