// Code generated by github.com/13k/geyser/apigen. DO NOT EDIT.

package geyser_test

import (
	"github.com/13k/geyser"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
)

func TestNewCSGOPlayers(t *testing.T) {
	client := &geyser.Client{}
	appIDs := []uint32{730}

	for _, appID := range appIDs {
		i, err := geyser.NewCSGOPlayers(client, appID)

		require.NoError(t, err)
		require.NotNil(t, i)

		assert.Same(t, client, i.Client)
		assert.NotNil(t, i.Interface)
	}
}

func TestCSGOPlayers_GetNextMatchSharingCode(t *testing.T) {
	var i *geyser.CSGOPlayers
	var err error
	var req *geyser.Request
	var result *geyser.CSGOPlayersGetNextMatchSharingCode
	var ok bool

	client := &geyser.Client{}

	i, err = geyser.NewCSGOPlayers(client, 730)

	require.NoError(t, err)
	require.NotNil(t, i)

	req, err = i.GetNextMatchSharingCode()

	require.NoError(t, err)
	require.NotNil(t, req)

	assert.Same(t, client, req.Client)
	assert.Same(t, i.Interface, req.Interface)

	if assert.NotNil(t, req.Method) {
		assert.Equal(t, "GetNextMatchSharingCode", req.Method.Name)
		assert.Equal(t, 1, req.Method.Version)
	}

	result, ok = req.Result.(*geyser.CSGOPlayersGetNextMatchSharingCode)

	if assert.Truef(t, ok, "invalid result type %T", result) {
		assert.NotNil(t, result)
	}
}
