// Code generated by github.com/13k/geyser/apigen. DO NOT EDIT.

package geyser_test

import (
	"github.com/13k/geyser"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
)

func TestNewSteamUserAuth(t *testing.T) {
	client := &geyser.Client{}
	i, err := geyser.NewSteamUserAuth(client)

	require.NoError(t, err)
	require.NotNil(t, i)

	assert.Same(t, client, i.Client)
	assert.NotNil(t, i.Interface)
}

func TestSteamUserAuth_AuthenticateUser(t *testing.T) {
	var i *geyser.SteamUserAuth
	var err error
	var req *geyser.Request
	var result *geyser.SteamUserAuthAuthenticateUser
	var ok bool

	client := &geyser.Client{}

	i, err = geyser.NewSteamUserAuth(client)

	require.NoError(t, err)
	require.NotNil(t, i)

	req, err = i.AuthenticateUser()

	require.NoError(t, err)
	require.NotNil(t, req)

	assert.Same(t, client, req.Client)
	assert.Same(t, i.Interface, req.Interface)

	if assert.NotNil(t, req.Method) {
		assert.Equal(t, "AuthenticateUser", req.Method.Name)
		assert.Equal(t, 1, req.Method.Version)
	}

	result, ok = req.Result.(*geyser.SteamUserAuthAuthenticateUser)

	if assert.Truef(t, ok, "invalid result type %T", result) {
		assert.NotNil(t, result)
	}
}

func TestSteamUserAuth_AuthenticateUserTicket(t *testing.T) {
	var i *geyser.SteamUserAuth
	var err error
	var req *geyser.Request
	var result *geyser.SteamUserAuthAuthenticateUserTicket
	var ok bool

	client := &geyser.Client{}

	i, err = geyser.NewSteamUserAuth(client)

	require.NoError(t, err)
	require.NotNil(t, i)

	req, err = i.AuthenticateUserTicket()

	require.NoError(t, err)
	require.NotNil(t, req)

	assert.Same(t, client, req.Client)
	assert.Same(t, i.Interface, req.Interface)

	if assert.NotNil(t, req.Method) {
		assert.Equal(t, "AuthenticateUserTicket", req.Method.Name)
		assert.Equal(t, 1, req.Method.Version)
	}

	result, ok = req.Result.(*geyser.SteamUserAuthAuthenticateUserTicket)

	if assert.Truef(t, ok, "invalid result type %T", result) {
		assert.NotNil(t, result)
	}
}
