// Code generated by github.com/13k/geyser/apigen. DO NOT EDIT.

package geyser_test

import (
	"github.com/13k/geyser"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
)

func TestNewSteamCDN(t *testing.T) {
	client := &geyser.Client{}
	i, err := geyser.NewSteamCDN(client)

	require.NoError(t, err)
	require.NotNil(t, i)

	assert.Same(t, client, i.Client)
	assert.NotNil(t, i.Interface)
}

func TestSteamCDN_SetClientFilters(t *testing.T) {
	var i *geyser.SteamCDN
	var err error
	var req *geyser.Request
	var result *geyser.SteamCDNSetClientFilters
	var ok bool

	client := &geyser.Client{}

	i, err = geyser.NewSteamCDN(client)

	require.NoError(t, err)
	require.NotNil(t, i)

	req, err = i.SetClientFilters()

	require.NoError(t, err)
	require.NotNil(t, req)

	assert.Same(t, client, req.Client)
	assert.Same(t, i.Interface, req.Interface)

	if assert.NotNil(t, req.Method) {
		assert.Equal(t, "SetClientFilters", req.Method.Name)
		assert.Equal(t, 1, req.Method.Version)
	}

	result, ok = req.Result.(*geyser.SteamCDNSetClientFilters)

	if assert.Truef(t, ok, "invalid result type %T", result) {
		assert.NotNil(t, result)
	}
}

func TestSteamCDN_SetPerformanceStats(t *testing.T) {
	var i *geyser.SteamCDN
	var err error
	var req *geyser.Request
	var result *geyser.SteamCDNSetPerformanceStats
	var ok bool

	client := &geyser.Client{}

	i, err = geyser.NewSteamCDN(client)

	require.NoError(t, err)
	require.NotNil(t, i)

	req, err = i.SetPerformanceStats()

	require.NoError(t, err)
	require.NotNil(t, req)

	assert.Same(t, client, req.Client)
	assert.Same(t, i.Interface, req.Interface)

	if assert.NotNil(t, req.Method) {
		assert.Equal(t, "SetPerformanceStats", req.Method.Name)
		assert.Equal(t, 1, req.Method.Version)
	}

	result, ok = req.Result.(*geyser.SteamCDNSetPerformanceStats)

	if assert.Truef(t, ok, "invalid result type %T", result) {
		assert.NotNil(t, result)
	}
}
