// Code generated by github.com/13k/geyser/apigen. DO NOT EDIT.

package geyser_test

import (
	"github.com/13k/geyser"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
)

func TestNewSteamWebAPIUtil(t *testing.T) {
	client := &geyser.Client{}
	i, err := geyser.NewSteamWebAPIUtil(client)

	require.NoError(t, err)
	require.NotNil(t, i)

	assert.Same(t, client, i.Client)
	assert.NotNil(t, i.Interface)
}

func TestSteamWebAPIUtil_GetServerInfo(t *testing.T) {
	var i *geyser.SteamWebAPIUtil
	var err error
	var req *geyser.Request
	var result *geyser.SteamWebAPIUtilGetServerInfo
	var ok bool

	client := &geyser.Client{}

	i, err = geyser.NewSteamWebAPIUtil(client)

	require.NoError(t, err)
	require.NotNil(t, i)

	req, err = i.GetServerInfo()

	require.NoError(t, err)
	require.NotNil(t, req)

	assert.Same(t, client, req.Client)
	assert.Same(t, i.Interface, req.Interface)

	if assert.NotNil(t, req.Method) {
		assert.Equal(t, "GetServerInfo", req.Method.Name)
		assert.Equal(t, 1, req.Method.Version)
	}

	result, ok = req.Result.(*geyser.SteamWebAPIUtilGetServerInfo)

	if assert.Truef(t, ok, "invalid result type %T", result) {
		assert.NotNil(t, result)
	}
}

func TestSteamWebAPIUtil_GetSupportedAPIList(t *testing.T) {
	var i *geyser.SteamWebAPIUtil
	var err error
	var req *geyser.Request
	var result *geyser.SteamWebAPIUtilGetSupportedAPIList
	var ok bool

	client := &geyser.Client{}

	i, err = geyser.NewSteamWebAPIUtil(client)

	require.NoError(t, err)
	require.NotNil(t, i)

	req, err = i.GetSupportedAPIList()

	require.NoError(t, err)
	require.NotNil(t, req)

	assert.Same(t, client, req.Client)
	assert.Same(t, i.Interface, req.Interface)

	if assert.NotNil(t, req.Method) {
		assert.Equal(t, "GetSupportedAPIList", req.Method.Name)
		assert.Equal(t, 1, req.Method.Version)
	}

	result, ok = req.Result.(*geyser.SteamWebAPIUtilGetSupportedAPIList)

	if assert.Truef(t, ok, "invalid result type %T", result) {
		assert.NotNil(t, result)
	}
}
