// Code generated by github.com/13k/geyser/apigen. DO NOT EDIT.

package geyser_test

import (
	"github.com/13k/geyser"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
)

func TestNewSteamRemoteStorage(t *testing.T) {
	client := &geyser.Client{}
	i, err := geyser.NewSteamRemoteStorage(client)

	require.NoError(t, err)
	require.NotNil(t, i)

	assert.Same(t, client, i.Client)
	assert.NotNil(t, i.Interface)
}

func TestSteamRemoteStorage_GetCollectionDetails(t *testing.T) {
	var i *geyser.SteamRemoteStorage
	var err error
	var req *geyser.Request
	var result *geyser.SteamRemoteStorageGetCollectionDetails
	var ok bool

	client := &geyser.Client{}

	i, err = geyser.NewSteamRemoteStorage(client)

	require.NoError(t, err)
	require.NotNil(t, i)

	req, err = i.GetCollectionDetails()

	require.NoError(t, err)
	require.NotNil(t, req)

	assert.Same(t, client, req.Client)
	assert.Same(t, i.Interface, req.Interface)

	if assert.NotNil(t, req.Method) {
		assert.Equal(t, "GetCollectionDetails", req.Method.Name)
		assert.Equal(t, 1, req.Method.Version)
	}

	result, ok = req.Result.(*geyser.SteamRemoteStorageGetCollectionDetails)

	if assert.Truef(t, ok, "invalid result type %T", result) {
		assert.NotNil(t, result)
	}
}

func TestSteamRemoteStorage_GetPublishedFileDetails(t *testing.T) {
	var i *geyser.SteamRemoteStorage
	var err error
	var req *geyser.Request
	var result *geyser.SteamRemoteStorageGetPublishedFileDetails
	var ok bool

	client := &geyser.Client{}

	i, err = geyser.NewSteamRemoteStorage(client)

	require.NoError(t, err)
	require.NotNil(t, i)

	req, err = i.GetPublishedFileDetails()

	require.NoError(t, err)
	require.NotNil(t, req)

	assert.Same(t, client, req.Client)
	assert.Same(t, i.Interface, req.Interface)

	if assert.NotNil(t, req.Method) {
		assert.Equal(t, "GetPublishedFileDetails", req.Method.Name)
		assert.Equal(t, 1, req.Method.Version)
	}

	result, ok = req.Result.(*geyser.SteamRemoteStorageGetPublishedFileDetails)

	if assert.Truef(t, ok, "invalid result type %T", result) {
		assert.NotNil(t, result)
	}
}

func TestSteamRemoteStorage_GetUGCFileDetails(t *testing.T) {
	var i *geyser.SteamRemoteStorage
	var err error
	var req *geyser.Request
	var result *geyser.SteamRemoteStorageGetUGCFileDetails
	var ok bool

	client := &geyser.Client{}

	i, err = geyser.NewSteamRemoteStorage(client)

	require.NoError(t, err)
	require.NotNil(t, i)

	req, err = i.GetUGCFileDetails()

	require.NoError(t, err)
	require.NotNil(t, req)

	assert.Same(t, client, req.Client)
	assert.Same(t, i.Interface, req.Interface)

	if assert.NotNil(t, req.Method) {
		assert.Equal(t, "GetUGCFileDetails", req.Method.Name)
		assert.Equal(t, 1, req.Method.Version)
	}

	result, ok = req.Result.(*geyser.SteamRemoteStorageGetUGCFileDetails)

	if assert.Truef(t, ok, "invalid result type %T", result) {
		assert.NotNil(t, result)
	}
}
