package main

var (
	filenamesSteam = map[string]string{
		"IBroadcastService":              "ibroadcast_service",
		"ICheatReportingService":         "icheat_reporting_service",
		"IClientStats":                   "iclient_stats",
		"IContentServerConfigService":    "icontent_server_config_service",
		"IContentServerDirectoryService": "icontent_server_directory_service",
		"ICSGOPlayers":                   "icsgo_players",
		"ICSGOServers":                   "icsgo_servers",
		"ICSGOTournaments":               "icsgo_tournaments",
		"IDOTA2Fantasy":                  "idota2_fantasy",
		"IDOTA2Match":                    "idota2_match",
		"IDOTA2MatchStats":               "idota2_match_stats",
		"IDOTA2StreamSystem":             "idota2_stream_system",
		"IDOTA2Ticket":                   "idota2_ticket",
		"IEconDOTA2":                     "iecon_dota2",
		"IEconItems":                     "iecon_items",
		"IEconService":                   "iecon_service",
		"IGameNotificationsService":      "igame_notifications_service",
		"IGameServersService":            "igame_servers_service",
		"IGCVersion":                     "igc_version",
		"IInventoryService":              "iinventory_service",
		"IPlayerService":                 "iplayer_service",
		"IPortal2Leaderboards":           "iportal2_leaderboards",
		"IPublishedFileService":          "ipublished_file_service",
		"ISteamApps":                     "isteam_apps",
		"ISteamBroadcast":                "isteam_broadcast",
		"ISteamCDN":                      "isteam_cdn",
		"ISteamDirectory":                "isteam_directory",
		"ISteamEconomy":                  "isteam_economy",
		"ISteamNews":                     "isteam_news",
		"ISteamRemoteStorage":            "isteam_remote_storage",
		"ISteamUserAuth":                 "isteam_user_auth",
		"ISteamUserOAuth":                "isteam_user_oauth",
		"ISteamUserStats":                "isteam_user_stats",
		"ISteamUser":                     "isteam_user",
		"ISteamWebAPIUtil":               "isteam_web_api_util",
		"ISteamWebUserPresenceOAuth":     "isteam_web_user_presence_oauth",
		"IStoreService":                  "istore_service",
		"ITFItems":                       "itf_items",
		"ITFPromos":                      "itf_promos",
		"ITFSystem":                      "itf_system",
		// undocumented interfaces
		"IAccountLinkingService":     "iaccount_linking_service",
		"ICloudService":              "icloud_service",
		"ICommunityService":          "icommunity_service",
		"ICredentialsService":        "icredentials_service",
		"IFriendMessagesService":     "ifriend_messages_service",
		"IGameCoordinator":           "igame_coordinator",
		"IGameInventory":             "igame_inventory",
		"IMobileAuthService":         "imobile_auth_service",
		"IMobileNotificationService": "imobile_notification_service",
		"IQuestService":              "iquest_service",
		"IRemoteClientService":       "iremote_client_service",
		"ISteamBitPay":               "isteam_bit_pay",
		"ISteamBoaCompra":            "isteam_boa_compra",
		"ISteamGameOAuth":            "isteam_game_oauth",
		"ISteamNodwin":               "isteam_nodwin",
		"ISteamPayPalPaymentsHub":    "isteam_paypal_payments_hub",
		"ISteamTVService":            "isteam_tv_service",
		"ITwoFactorService":          "itwo_factor_service",
		"IVideoService":              "ivideo_service",
	}

	filenamesDota = map[string]string{
		"IChat":                  "ichat",
		"ICustomGames":           "icustom_games",
		"IDOTA2AutomatedTourney": "idota2_automated_tourney",
		"IDOTA2DPC":              "idota2_dpc",
		"IDOTA2Events":           "idota2_events",
		"IDOTA2Fantasy":          "idota2_fantasy",
		"IDOTA2League":           "idota2_league",
		"IDOTA2Match":            "idota2_match",
		"IDOTA2MatchStats":       "idota2_match_stats",
		"IDOTA2Operations":       "idota2_operations",
		"IDOTA2Plus":             "idota2_plus",
		"IDOTA2StreamSystem":     "idota2_stream_system",
		"IDOTA2Teams":            "idota2_teams",
		"IFrontpage":             "ifrontpage",
		"ILeague":                "ileague",
		"ILobbies":               "ilobbies",
		"IStore":                 "istore",
		"ITournaments":           "itournaments",
		"IWorkshop":              "iworkshop",
	}
)
