// Code generated by geyser. DO NOT EDIT.

package steam_test

import (
	"github.com/13k/geyser/v2"
	"github.com/13k/geyser/v2/steam"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
)

func TestNewIContentServerConfigService(t *testing.T) {
	client, err := steam.New()

	require.NoError(t, err)
	require.NotNil(t, client)

	ci, err := steam.NewIContentServerConfigService(client)

	require.NoError(t, err)
	require.NotNil(t, ci)

	assert.Same(t, client, ci.Client)
	assert.NotNil(t, ci.Interface)
}

func TestIContentServerConfigService_GetSteamCacheNodeParams(t *testing.T) {
	var ci *steam.IContentServerConfigService
	var err error
	var req *geyser.Request

	client, err := steam.New()

	require.NoError(t, err)
	require.NotNil(t, client)

	ci, err = steam.NewIContentServerConfigService(client)

	require.NoError(t, err)
	require.NotNil(t, ci)

	req, err = ci.GetSteamCacheNodeParams()

	require.NoError(t, err)
	require.NotNil(t, req)

	assert.Same(t, ci.Interface, req.Interface)

	if assert.NotNil(t, req.Method) {
		assert.Equal(t, "GetSteamCacheNodeParams", req.Method.Name)
		assert.Equal(t, 1, req.Method.Version)
	}
}

func TestIContentServerConfigService_SetSteamCacheClientFilters(t *testing.T) {
	var ci *steam.IContentServerConfigService
	var err error
	var req *geyser.Request

	client, err := steam.New()

	require.NoError(t, err)
	require.NotNil(t, client)

	ci, err = steam.NewIContentServerConfigService(client)

	require.NoError(t, err)
	require.NotNil(t, ci)

	req, err = ci.SetSteamCacheClientFilters()

	require.NoError(t, err)
	require.NotNil(t, req)

	assert.Same(t, ci.Interface, req.Interface)

	if assert.NotNil(t, req.Method) {
		assert.Equal(t, "SetSteamCacheClientFilters", req.Method.Name)
		assert.Equal(t, 1, req.Method.Version)
	}
}

func TestIContentServerConfigService_SetSteamCachePerformanceStats(t *testing.T) {
	var ci *steam.IContentServerConfigService
	var err error
	var req *geyser.Request

	client, err := steam.New()

	require.NoError(t, err)
	require.NotNil(t, client)

	ci, err = steam.NewIContentServerConfigService(client)

	require.NoError(t, err)
	require.NotNil(t, ci)

	req, err = ci.SetSteamCachePerformanceStats()

	require.NoError(t, err)
	require.NotNil(t, req)

	assert.Same(t, ci.Interface, req.Interface)

	if assert.NotNil(t, req.Method) {
		assert.Equal(t, "SetSteamCachePerformanceStats", req.Method.Name)
		assert.Equal(t, 1, req.Method.Version)
	}
}
