// Code generated by geyser. DO NOT EDIT.
// API interface: ICSGOTournaments.

package steam

import (
	"github.com/13k/geyser"
	"github.com/13k/geyser/schema"
	"net/http"
)

// SchemaICSGOTournaments stores the Interfaces for interface ICSGOTournaments.
var SchemaICSGOTournaments = schema.MustNewInterfaces(
	&schema.Interface{
		Methods: schema.MustNewMethods(
			&schema.Method{
				HTTPMethod: http.MethodGet,
				Name:       "GetTournamentFantasyLineup",
				Params: schema.NewMethodParams(
					&schema.MethodParam{
						Description: "The event ID",
						Name:        "event",
						Optional:    false,
						Type:        "uint32",
					},
					&schema.MethodParam{
						Description: "The SteamID of the user inventory",
						Name:        "steamid",
						Optional:    false,
						Type:        "uint64",
					},
					&schema.MethodParam{
						Description: "Authentication obtained from the SteamID",
						Name:        "steamidkey",
						Optional:    false,
						Type:        "string",
					},
				),
				Undocumented: false,
				Version:      1,
			},
			&schema.Method{
				HTTPMethod: http.MethodGet,
				Name:       "GetTournamentItems",
				Params: schema.NewMethodParams(
					&schema.MethodParam{
						Description: "The event ID",
						Name:        "event",
						Optional:    false,
						Type:        "uint32",
					},
					&schema.MethodParam{
						Description: "The SteamID of the user inventory",
						Name:        "steamid",
						Optional:    false,
						Type:        "uint64",
					},
					&schema.MethodParam{
						Description: "Authentication obtained from the SteamID",
						Name:        "steamidkey",
						Optional:    false,
						Type:        "string",
					},
				),
				Undocumented: false,
				Version:      1,
			},
			&schema.Method{
				HTTPMethod: http.MethodGet,
				Name:       "GetTournamentLayout",
				Params: schema.NewMethodParams(
					&schema.MethodParam{
						Description: "The event ID",
						Name:        "event",
						Optional:    false,
						Type:        "uint32",
					},
				),
				Undocumented: false,
				Version:      1,
			},
			&schema.Method{
				HTTPMethod: http.MethodGet,
				Name:       "GetTournamentPredictions",
				Params: schema.NewMethodParams(
					&schema.MethodParam{
						Description: "The event ID",
						Name:        "event",
						Optional:    false,
						Type:        "uint32",
					},
					&schema.MethodParam{
						Description: "The SteamID of the user inventory",
						Name:        "steamid",
						Optional:    false,
						Type:        "uint64",
					},
					&schema.MethodParam{
						Description: "Authentication obtained from the SteamID",
						Name:        "steamidkey",
						Optional:    false,
						Type:        "string",
					},
				),
				Undocumented: false,
				Version:      1,
			},
			&schema.Method{
				HTTPMethod: http.MethodPost,
				Name:       "UploadTournamentFantasyLineup",
				Params: schema.NewMethodParams(
					&schema.MethodParam{
						Description: "The event ID",
						Name:        "event",
						Optional:    false,
						Type:        "uint32",
					},
					&schema.MethodParam{
						Description: "The SteamID of the user inventory",
						Name:        "steamid",
						Optional:    false,
						Type:        "uint64",
					},
					&schema.MethodParam{
						Description: "Authentication obtained from the SteamID",
						Name:        "steamidkey",
						Optional:    false,
						Type:        "string",
					},
					&schema.MethodParam{
						Description: "Event section id",
						Name:        "sectionid",
						Optional:    false,
						Type:        "uint32",
					},
					&schema.MethodParam{
						Description: "PickID to select for the slot",
						Name:        "pickid0",
						Optional:    false,
						Type:        "uint32",
					},
					&schema.MethodParam{
						Description: "ItemID to lock in for the pick",
						Name:        "itemid0",
						Optional:    false,
						Type:        "uint64",
					},
					&schema.MethodParam{
						Description: "PickID to select for the slot",
						Name:        "pickid1",
						Optional:    false,
						Type:        "uint32",
					},
					&schema.MethodParam{
						Description: "ItemID to lock in for the pick",
						Name:        "itemid1",
						Optional:    false,
						Type:        "uint64",
					},
					&schema.MethodParam{
						Description: "PickID to select for the slot",
						Name:        "pickid2",
						Optional:    false,
						Type:        "uint32",
					},
					&schema.MethodParam{
						Description: "ItemID to lock in for the pick",
						Name:        "itemid2",
						Optional:    false,
						Type:        "uint64",
					},
					&schema.MethodParam{
						Description: "PickID to select for the slot",
						Name:        "pickid3",
						Optional:    false,
						Type:        "uint32",
					},
					&schema.MethodParam{
						Description: "ItemID to lock in for the pick",
						Name:        "itemid3",
						Optional:    false,
						Type:        "uint64",
					},
					&schema.MethodParam{
						Description: "PickID to select for the slot",
						Name:        "pickid4",
						Optional:    false,
						Type:        "uint32",
					},
					&schema.MethodParam{
						Description: "ItemID to lock in for the pick",
						Name:        "itemid4",
						Optional:    false,
						Type:        "uint64",
					},
				),
				Undocumented: false,
				Version:      1,
			},
			&schema.Method{
				HTTPMethod: http.MethodPost,
				Name:       "UploadTournamentPredictions",
				Params: schema.NewMethodParams(
					&schema.MethodParam{
						Description: "The event ID",
						Name:        "event",
						Optional:    false,
						Type:        "uint32",
					},
					&schema.MethodParam{
						Description: "The SteamID of the user inventory",
						Name:        "steamid",
						Optional:    false,
						Type:        "uint64",
					},
					&schema.MethodParam{
						Description: "Authentication obtained from the SteamID",
						Name:        "steamidkey",
						Optional:    false,
						Type:        "string",
					},
					&schema.MethodParam{
						Description: "Event section id",
						Name:        "sectionid",
						Optional:    false,
						Type:        "uint32",
					},
					&schema.MethodParam{
						Description: "Event group id",
						Name:        "groupid",
						Optional:    false,
						Type:        "uint32",
					},
					&schema.MethodParam{
						Description: "Index in group",
						Name:        "index",
						Optional:    false,
						Type:        "uint32",
					},
					&schema.MethodParam{
						Description: "Pick ID to select",
						Name:        "pickid",
						Optional:    false,
						Type:        "uint32",
					},
					&schema.MethodParam{
						Description: "ItemID to lock in for the pick",
						Name:        "itemid",
						Optional:    false,
						Type:        "uint64",
					},
				),
				Undocumented: false,
				Version:      1,
			},
		),
		Name:         "ICSGOTournaments_730",
		Undocumented: false,
	},
)

// ICSGOTournaments represents interface ICSGOTournaments.
//
// Supported AppIDs: 730.
type ICSGOTournaments struct {
	Client    *Client
	Interface *schema.Interface
}

// NewICSGOTournaments creates a new ICSGOTournaments interface.
//
// Supported AppIDs: 730.
func NewICSGOTournaments(c *Client, appID uint32) (*ICSGOTournaments, error) {
	si, err := SchemaICSGOTournaments.Get(schema.InterfaceKey{
		AppID: appID,
		Name:  "ICSGOTournaments",
	})

	if err != nil {
		return nil, err
	}

	s := &ICSGOTournaments{
		Client:    c,
		Interface: si,
	}

	return s, nil
}

// ICSGOTournaments creates a new ICSGOTournaments interface.
//
// Supported AppIDs: 730.
func (c *Client) ICSGOTournaments(appID uint32) (*ICSGOTournaments, error) {
	return NewICSGOTournaments(c, appID)
}

/*
GetTournamentFantasyLineup creates a Request for interface method GetTournamentFantasyLineup.

Parameters

  * event [uint32] (required): The event ID
  * steamid [uint64] (required): The SteamID of the user inventory
  * steamidkey [string] (required): Authentication obtained from the SteamID
*/
func (i *ICSGOTournaments) GetTournamentFantasyLineup() (*geyser.Request, error) {
	sm, err := i.Interface.Methods.Get(schema.MethodKey{
		Name:    "GetTournamentFantasyLineup",
		Version: 1,
	})

	if err != nil {
		return nil, err
	}

	req := &geyser.Request{
		Client:    i.Client,
		Interface: i.Interface,
		Method:    sm,
	}

	return req, nil
}

/*
GetTournamentItems creates a Request for interface method GetTournamentItems.

Parameters

  * event [uint32] (required): The event ID
  * steamid [uint64] (required): The SteamID of the user inventory
  * steamidkey [string] (required): Authentication obtained from the SteamID
*/
func (i *ICSGOTournaments) GetTournamentItems() (*geyser.Request, error) {
	sm, err := i.Interface.Methods.Get(schema.MethodKey{
		Name:    "GetTournamentItems",
		Version: 1,
	})

	if err != nil {
		return nil, err
	}

	req := &geyser.Request{
		Client:    i.Client,
		Interface: i.Interface,
		Method:    sm,
	}

	return req, nil
}

/*
GetTournamentLayout creates a Request for interface method GetTournamentLayout.

Parameters

  * event [uint32] (required): The event ID
*/
func (i *ICSGOTournaments) GetTournamentLayout() (*geyser.Request, error) {
	sm, err := i.Interface.Methods.Get(schema.MethodKey{
		Name:    "GetTournamentLayout",
		Version: 1,
	})

	if err != nil {
		return nil, err
	}

	req := &geyser.Request{
		Client:    i.Client,
		Interface: i.Interface,
		Method:    sm,
	}

	return req, nil
}

/*
GetTournamentPredictions creates a Request for interface method GetTournamentPredictions.

Parameters

  * event [uint32] (required): The event ID
  * steamid [uint64] (required): The SteamID of the user inventory
  * steamidkey [string] (required): Authentication obtained from the SteamID
*/
func (i *ICSGOTournaments) GetTournamentPredictions() (*geyser.Request, error) {
	sm, err := i.Interface.Methods.Get(schema.MethodKey{
		Name:    "GetTournamentPredictions",
		Version: 1,
	})

	if err != nil {
		return nil, err
	}

	req := &geyser.Request{
		Client:    i.Client,
		Interface: i.Interface,
		Method:    sm,
	}

	return req, nil
}

/*
UploadTournamentFantasyLineup creates a Request for interface method UploadTournamentFantasyLineup.

Parameters

  * event [uint32] (required): The event ID
  * steamid [uint64] (required): The SteamID of the user inventory
  * steamidkey [string] (required): Authentication obtained from the SteamID
  * sectionid [uint32] (required): Event section id
  * pickid0 [uint32] (required): PickID to select for the slot
  * itemid0 [uint64] (required): ItemID to lock in for the pick
  * pickid1 [uint32] (required): PickID to select for the slot
  * itemid1 [uint64] (required): ItemID to lock in for the pick
  * pickid2 [uint32] (required): PickID to select for the slot
  * itemid2 [uint64] (required): ItemID to lock in for the pick
  * pickid3 [uint32] (required): PickID to select for the slot
  * itemid3 [uint64] (required): ItemID to lock in for the pick
  * pickid4 [uint32] (required): PickID to select for the slot
  * itemid4 [uint64] (required): ItemID to lock in for the pick
*/
func (i *ICSGOTournaments) UploadTournamentFantasyLineup() (*geyser.Request, error) {
	sm, err := i.Interface.Methods.Get(schema.MethodKey{
		Name:    "UploadTournamentFantasyLineup",
		Version: 1,
	})

	if err != nil {
		return nil, err
	}

	req := &geyser.Request{
		Client:    i.Client,
		Interface: i.Interface,
		Method:    sm,
	}

	return req, nil
}

/*
UploadTournamentPredictions creates a Request for interface method UploadTournamentPredictions.

Parameters

  * event [uint32] (required): The event ID
  * steamid [uint64] (required): The SteamID of the user inventory
  * steamidkey [string] (required): Authentication obtained from the SteamID
  * sectionid [uint32] (required): Event section id
  * groupid [uint32] (required): Event group id
  * index [uint32] (required): Index in group
  * pickid [uint32] (required): Pick ID to select
  * itemid [uint64] (required): ItemID to lock in for the pick
*/
func (i *ICSGOTournaments) UploadTournamentPredictions() (*geyser.Request, error) {
	sm, err := i.Interface.Methods.Get(schema.MethodKey{
		Name:    "UploadTournamentPredictions",
		Version: 1,
	})

	if err != nil {
		return nil, err
	}

	req := &geyser.Request{
		Client:    i.Client,
		Interface: i.Interface,
		Method:    sm,
	}

	return req, nil
}
