// Code generated by geyser. DO NOT EDIT.

package steam_test

import (
	"github.com/13k/geyser"
	"github.com/13k/geyser/steam"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
)

func TestNewICSGOServers(t *testing.T) {
	client, err := steam.New()

	require.NoError(t, err)
	require.NotNil(t, client)

	appIDs := []uint32{730}

	for _, appID := range appIDs {
		ci, err := steam.NewICSGOServers(client, appID)

		require.NoError(t, err)
		require.NotNil(t, ci)

		assert.Same(t, client, ci.Client)
		assert.NotNil(t, ci.Interface)
	}
}

func TestICSGOServers_GetGameMapsPlaytime(t *testing.T) {
	var ci *steam.ICSGOServers
	var err error
	var req *geyser.Request

	client, err := steam.New()

	require.NoError(t, err)
	require.NotNil(t, client)

	ci, err = steam.NewICSGOServers(client, 730)

	require.NoError(t, err)
	require.NotNil(t, ci)

	req, err = ci.GetGameMapsPlaytime()

	require.NoError(t, err)
	require.NotNil(t, req)

	assert.Same(t, ci.Interface, req.Interface)

	if assert.NotNil(t, req.Method) {
		assert.Equal(t, "GetGameMapsPlaytime", req.Method.Name)
		assert.Equal(t, 1, req.Method.Version)
	}
}

func TestICSGOServers_GetGameServersStatus(t *testing.T) {
	var ci *steam.ICSGOServers
	var err error
	var req *geyser.Request

	client, err := steam.New()

	require.NoError(t, err)
	require.NotNil(t, client)

	ci, err = steam.NewICSGOServers(client, 730)

	require.NoError(t, err)
	require.NotNil(t, ci)

	req, err = ci.GetGameServersStatus()

	require.NoError(t, err)
	require.NotNil(t, req)

	assert.Same(t, ci.Interface, req.Interface)

	if assert.NotNil(t, req.Method) {
		assert.Equal(t, "GetGameServersStatus", req.Method.Name)
		assert.Equal(t, 1, req.Method.Version)
	}
}
