// Code generated by geyser. DO NOT EDIT.

package steam_test

import (
	"github.com/13k/geyser/v2"
	"github.com/13k/geyser/v2/steam"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
)

func TestNewIDOTA2Fantasy(t *testing.T) {
	client, err := steam.New()

	require.NoError(t, err)
	require.NotNil(t, client)

	appIDs := []uint32{205790}

	for _, appID := range appIDs {
		ci, err := steam.NewIDOTA2Fantasy(client, appID)

		require.NoError(t, err)
		require.NotNil(t, ci)

		assert.Same(t, client, ci.Client)
		assert.NotNil(t, ci.Interface)
	}
}

func TestIDOTA2Fantasy_GetFantasyPlayerStats(t *testing.T) {
	var ci *steam.IDOTA2Fantasy
	var err error
	var req *geyser.Request

	client, err := steam.New()

	require.NoError(t, err)
	require.NotNil(t, client)

	ci, err = steam.NewIDOTA2Fantasy(client, 205790)

	require.NoError(t, err)
	require.NotNil(t, ci)

	req, err = ci.GetFantasyPlayerStats()

	require.NoError(t, err)
	require.NotNil(t, req)

	assert.Same(t, ci.Interface, req.Interface)

	if assert.NotNil(t, req.Method) {
		assert.Equal(t, "GetFantasyPlayerStats", req.Method.Name)
		assert.Equal(t, 1, req.Method.Version)
	}
}

func TestIDOTA2Fantasy_GetPlayerOfficialInfo(t *testing.T) {
	var ci *steam.IDOTA2Fantasy
	var err error
	var req *geyser.Request

	client, err := steam.New()

	require.NoError(t, err)
	require.NotNil(t, client)

	ci, err = steam.NewIDOTA2Fantasy(client, 205790)

	require.NoError(t, err)
	require.NotNil(t, ci)

	req, err = ci.GetPlayerOfficialInfo()

	require.NoError(t, err)
	require.NotNil(t, req)

	assert.Same(t, ci.Interface, req.Interface)

	if assert.NotNil(t, req.Method) {
		assert.Equal(t, "GetPlayerOfficialInfo", req.Method.Name)
		assert.Equal(t, 1, req.Method.Version)
	}
}

func TestIDOTA2Fantasy_GetProPlayerList(t *testing.T) {
	var ci *steam.IDOTA2Fantasy
	var err error
	var req *geyser.Request

	client, err := steam.New()

	require.NoError(t, err)
	require.NotNil(t, client)

	ci, err = steam.NewIDOTA2Fantasy(client, 205790)

	require.NoError(t, err)
	require.NotNil(t, ci)

	req, err = ci.GetProPlayerList()

	require.NoError(t, err)
	require.NotNil(t, req)

	assert.Same(t, ci.Interface, req.Interface)

	if assert.NotNil(t, req.Method) {
		assert.Equal(t, "GetProPlayerList", req.Method.Name)
		assert.Equal(t, 1, req.Method.Version)
	}
}
