// Code generated by geyser. DO NOT EDIT.

package steam_test

import (
	"github.com/13k/geyser/v2"
	"github.com/13k/geyser/v2/schema"
	"github.com/13k/geyser/v2/steam"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
)

func TestNewIDOTA2Match(t *testing.T) {
	client, err := steam.New()

	require.NoError(t, err)
	require.NotNil(t, client)

	appIDs := []uint32{570, 205790}

	for _, appID := range appIDs {
		ci, err := steam.NewIDOTA2Match(client, appID)

		require.NoError(t, err)
		require.NotNil(t, ci)

		assert.Same(t, client, ci.Client)
		assert.NotNil(t, ci.Interface)
	}
}

func TestIDOTA2Match_GetLeagueListing(t *testing.T) {
	var ci *steam.IDOTA2Match
	var err error
	var req *geyser.Request
	var ok bool

	client, err := steam.New()

	require.NoError(t, err)
	require.NotNil(t, client)

	ci, err = steam.NewIDOTA2Match(client, 570)

	require.NoError(t, err)
	require.NotNil(t, ci)

	req, err = ci.GetLeagueListing()

	require.Error(t, err)

	_, ok = err.(*schema.InterfaceMethodNotFoundError)

	assert.Truef(t, ok, "invalid error type %T", err)

	ci, err = steam.NewIDOTA2Match(client, 205790)

	require.NoError(t, err)
	require.NotNil(t, ci)

	req, err = ci.GetLeagueListing()

	require.NoError(t, err)
	require.NotNil(t, req)

	assert.Same(t, ci.Interface, req.Interface)

	if assert.NotNil(t, req.Method) {
		assert.Equal(t, "GetLeagueListing", req.Method.Name)
		assert.Equal(t, 1, req.Method.Version)
	}
}

func TestIDOTA2Match_GetLiveLeagueGames(t *testing.T) {
	var ci *steam.IDOTA2Match
	var err error
	var req *geyser.Request

	client, err := steam.New()

	require.NoError(t, err)
	require.NotNil(t, client)

	ci, err = steam.NewIDOTA2Match(client, 570)

	require.NoError(t, err)
	require.NotNil(t, ci)

	req, err = ci.GetLiveLeagueGames()

	require.NoError(t, err)
	require.NotNil(t, req)

	assert.Same(t, ci.Interface, req.Interface)

	if assert.NotNil(t, req.Method) {
		assert.Equal(t, "GetLiveLeagueGames", req.Method.Name)
		assert.Equal(t, 1, req.Method.Version)
	}

	ci, err = steam.NewIDOTA2Match(client, 205790)

	require.NoError(t, err)
	require.NotNil(t, ci)

	req, err = ci.GetLiveLeagueGames()

	require.NoError(t, err)
	require.NotNil(t, req)

	assert.Same(t, ci.Interface, req.Interface)

	if assert.NotNil(t, req.Method) {
		assert.Equal(t, "GetLiveLeagueGames", req.Method.Name)
		assert.Equal(t, 1, req.Method.Version)
	}
}

func TestIDOTA2Match_GetMatchDetails(t *testing.T) {
	var ci *steam.IDOTA2Match
	var err error
	var req *geyser.Request

	client, err := steam.New()

	require.NoError(t, err)
	require.NotNil(t, client)

	ci, err = steam.NewIDOTA2Match(client, 570)

	require.NoError(t, err)
	require.NotNil(t, ci)

	req, err = ci.GetMatchDetails()

	require.NoError(t, err)
	require.NotNil(t, req)

	assert.Same(t, ci.Interface, req.Interface)

	if assert.NotNil(t, req.Method) {
		assert.Equal(t, "GetMatchDetails", req.Method.Name)
		assert.Equal(t, 1, req.Method.Version)
	}

	ci, err = steam.NewIDOTA2Match(client, 205790)

	require.NoError(t, err)
	require.NotNil(t, ci)

	req, err = ci.GetMatchDetails()

	require.NoError(t, err)
	require.NotNil(t, req)

	assert.Same(t, ci.Interface, req.Interface)

	if assert.NotNil(t, req.Method) {
		assert.Equal(t, "GetMatchDetails", req.Method.Name)
		assert.Equal(t, 1, req.Method.Version)
	}
}

func TestIDOTA2Match_GetMatchHistory(t *testing.T) {
	var ci *steam.IDOTA2Match
	var err error
	var req *geyser.Request

	client, err := steam.New()

	require.NoError(t, err)
	require.NotNil(t, client)

	ci, err = steam.NewIDOTA2Match(client, 570)

	require.NoError(t, err)
	require.NotNil(t, ci)

	req, err = ci.GetMatchHistory()

	require.NoError(t, err)
	require.NotNil(t, req)

	assert.Same(t, ci.Interface, req.Interface)

	if assert.NotNil(t, req.Method) {
		assert.Equal(t, "GetMatchHistory", req.Method.Name)
		assert.Equal(t, 1, req.Method.Version)
	}

	ci, err = steam.NewIDOTA2Match(client, 205790)

	require.NoError(t, err)
	require.NotNil(t, ci)

	req, err = ci.GetMatchHistory()

	require.NoError(t, err)
	require.NotNil(t, req)

	assert.Same(t, ci.Interface, req.Interface)

	if assert.NotNil(t, req.Method) {
		assert.Equal(t, "GetMatchHistory", req.Method.Name)
		assert.Equal(t, 1, req.Method.Version)
	}
}

func TestIDOTA2Match_GetMatchHistoryBySequenceNum(t *testing.T) {
	var ci *steam.IDOTA2Match
	var err error
	var req *geyser.Request

	client, err := steam.New()

	require.NoError(t, err)
	require.NotNil(t, client)

	ci, err = steam.NewIDOTA2Match(client, 570)

	require.NoError(t, err)
	require.NotNil(t, ci)

	req, err = ci.GetMatchHistoryBySequenceNum()

	require.NoError(t, err)
	require.NotNil(t, req)

	assert.Same(t, ci.Interface, req.Interface)

	if assert.NotNil(t, req.Method) {
		assert.Equal(t, "GetMatchHistoryBySequenceNum", req.Method.Name)
		assert.Equal(t, 1, req.Method.Version)
	}

	ci, err = steam.NewIDOTA2Match(client, 205790)

	require.NoError(t, err)
	require.NotNil(t, ci)

	req, err = ci.GetMatchHistoryBySequenceNum()

	require.NoError(t, err)
	require.NotNil(t, req)

	assert.Same(t, ci.Interface, req.Interface)

	if assert.NotNil(t, req.Method) {
		assert.Equal(t, "GetMatchHistoryBySequenceNum", req.Method.Name)
		assert.Equal(t, 1, req.Method.Version)
	}
}

func TestIDOTA2Match_GetTeamInfoByTeamID(t *testing.T) {
	var ci *steam.IDOTA2Match
	var err error
	var req *geyser.Request

	client, err := steam.New()

	require.NoError(t, err)
	require.NotNil(t, client)

	ci, err = steam.NewIDOTA2Match(client, 570)

	require.NoError(t, err)
	require.NotNil(t, ci)

	req, err = ci.GetTeamInfoByTeamID()

	require.NoError(t, err)
	require.NotNil(t, req)

	assert.Same(t, ci.Interface, req.Interface)

	if assert.NotNil(t, req.Method) {
		assert.Equal(t, "GetTeamInfoByTeamID", req.Method.Name)
		assert.Equal(t, 1, req.Method.Version)
	}

	ci, err = steam.NewIDOTA2Match(client, 205790)

	require.NoError(t, err)
	require.NotNil(t, ci)

	req, err = ci.GetTeamInfoByTeamID()

	require.NoError(t, err)
	require.NotNil(t, req)

	assert.Same(t, ci.Interface, req.Interface)

	if assert.NotNil(t, req.Method) {
		assert.Equal(t, "GetTeamInfoByTeamID", req.Method.Name)
		assert.Equal(t, 1, req.Method.Version)
	}
}

func TestIDOTA2Match_GetTopLiveEventGame(t *testing.T) {
	var ci *steam.IDOTA2Match
	var err error
	var req *geyser.Request

	client, err := steam.New()

	require.NoError(t, err)
	require.NotNil(t, client)

	ci, err = steam.NewIDOTA2Match(client, 570)

	require.NoError(t, err)
	require.NotNil(t, ci)

	req, err = ci.GetTopLiveEventGame()

	require.NoError(t, err)
	require.NotNil(t, req)

	assert.Same(t, ci.Interface, req.Interface)

	if assert.NotNil(t, req.Method) {
		assert.Equal(t, "GetTopLiveEventGame", req.Method.Name)
		assert.Equal(t, 1, req.Method.Version)
	}

	ci, err = steam.NewIDOTA2Match(client, 205790)

	require.NoError(t, err)
	require.NotNil(t, ci)

	req, err = ci.GetTopLiveEventGame()

	require.NoError(t, err)
	require.NotNil(t, req)

	assert.Same(t, ci.Interface, req.Interface)

	if assert.NotNil(t, req.Method) {
		assert.Equal(t, "GetTopLiveEventGame", req.Method.Name)
		assert.Equal(t, 1, req.Method.Version)
	}
}

func TestIDOTA2Match_GetTopLiveGame(t *testing.T) {
	var ci *steam.IDOTA2Match
	var err error
	var req *geyser.Request

	client, err := steam.New()

	require.NoError(t, err)
	require.NotNil(t, client)

	ci, err = steam.NewIDOTA2Match(client, 570)

	require.NoError(t, err)
	require.NotNil(t, ci)

	req, err = ci.GetTopLiveGame()

	require.NoError(t, err)
	require.NotNil(t, req)

	assert.Same(t, ci.Interface, req.Interface)

	if assert.NotNil(t, req.Method) {
		assert.Equal(t, "GetTopLiveGame", req.Method.Name)
		assert.Equal(t, 1, req.Method.Version)
	}

	ci, err = steam.NewIDOTA2Match(client, 205790)

	require.NoError(t, err)
	require.NotNil(t, ci)

	req, err = ci.GetTopLiveGame()

	require.NoError(t, err)
	require.NotNil(t, req)

	assert.Same(t, ci.Interface, req.Interface)

	if assert.NotNil(t, req.Method) {
		assert.Equal(t, "GetTopLiveGame", req.Method.Name)
		assert.Equal(t, 1, req.Method.Version)
	}
}

func TestIDOTA2Match_GetTopWeekendTourneyGames(t *testing.T) {
	var ci *steam.IDOTA2Match
	var err error
	var req *geyser.Request

	client, err := steam.New()

	require.NoError(t, err)
	require.NotNil(t, client)

	ci, err = steam.NewIDOTA2Match(client, 570)

	require.NoError(t, err)
	require.NotNil(t, ci)

	req, err = ci.GetTopWeekendTourneyGames()

	require.NoError(t, err)
	require.NotNil(t, req)

	assert.Same(t, ci.Interface, req.Interface)

	if assert.NotNil(t, req.Method) {
		assert.Equal(t, "GetTopWeekendTourneyGames", req.Method.Name)
		assert.Equal(t, 1, req.Method.Version)
	}

	ci, err = steam.NewIDOTA2Match(client, 205790)

	require.NoError(t, err)
	require.NotNil(t, ci)

	req, err = ci.GetTopWeekendTourneyGames()

	require.NoError(t, err)
	require.NotNil(t, req)

	assert.Same(t, ci.Interface, req.Interface)

	if assert.NotNil(t, req.Method) {
		assert.Equal(t, "GetTopWeekendTourneyGames", req.Method.Name)
		assert.Equal(t, 1, req.Method.Version)
	}
}

func TestIDOTA2Match_GetTournamentPlayerStats(t *testing.T) {
	var ci *steam.IDOTA2Match
	var err error
	var req *geyser.Request

	client, err := steam.New()

	require.NoError(t, err)
	require.NotNil(t, client)

	ci, err = steam.NewIDOTA2Match(client, 570)

	require.NoError(t, err)
	require.NotNil(t, ci)

	req, err = ci.GetTournamentPlayerStats(1)

	require.NoError(t, err)
	require.NotNil(t, req)

	assert.Same(t, ci.Interface, req.Interface)

	if assert.NotNil(t, req.Method) {
		assert.Equal(t, "GetTournamentPlayerStats", req.Method.Name)
		assert.Equal(t, 1, req.Method.Version)
	}

	ci, err = steam.NewIDOTA2Match(client, 570)

	require.NoError(t, err)
	require.NotNil(t, ci)

	req, err = ci.GetTournamentPlayerStats(2)

	require.NoError(t, err)
	require.NotNil(t, req)

	assert.Same(t, ci.Interface, req.Interface)

	if assert.NotNil(t, req.Method) {
		assert.Equal(t, "GetTournamentPlayerStats", req.Method.Name)
		assert.Equal(t, 2, req.Method.Version)
	}

	ci, err = steam.NewIDOTA2Match(client, 205790)

	require.NoError(t, err)
	require.NotNil(t, ci)

	req, err = ci.GetTournamentPlayerStats(1)

	require.NoError(t, err)
	require.NotNil(t, req)

	assert.Same(t, ci.Interface, req.Interface)

	if assert.NotNil(t, req.Method) {
		assert.Equal(t, "GetTournamentPlayerStats", req.Method.Name)
		assert.Equal(t, 1, req.Method.Version)
	}

	ci, err = steam.NewIDOTA2Match(client, 205790)

	require.NoError(t, err)
	require.NotNil(t, ci)

	req, err = ci.GetTournamentPlayerStats(2)

	require.NoError(t, err)
	require.NotNil(t, req)

	assert.Same(t, ci.Interface, req.Interface)

	if assert.NotNil(t, req.Method) {
		assert.Equal(t, "GetTournamentPlayerStats", req.Method.Name)
		assert.Equal(t, 2, req.Method.Version)
	}
}
