// Code generated by geyser. DO NOT EDIT.

package steam_test

import (
	"github.com/13k/geyser/v2"
	"github.com/13k/geyser/v2/steam"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
)

func TestNewIFriendMessagesService(t *testing.T) {
	client, err := steam.New()

	require.NoError(t, err)
	require.NotNil(t, client)

	ci, err := steam.NewIFriendMessagesService(client)

	require.NoError(t, err)
	require.NotNil(t, ci)

	assert.Same(t, client, ci.Client)
	assert.NotNil(t, ci.Interface)
}

func TestIFriendMessagesService_GetActiveMessageSessions(t *testing.T) {
	var ci *steam.IFriendMessagesService
	var err error
	var req *geyser.Request

	client, err := steam.New()

	require.NoError(t, err)
	require.NotNil(t, client)

	ci, err = steam.NewIFriendMessagesService(client)

	require.NoError(t, err)
	require.NotNil(t, ci)

	req, err = ci.GetActiveMessageSessions()

	require.NoError(t, err)
	require.NotNil(t, req)

	assert.Same(t, ci.Interface, req.Interface)

	if assert.NotNil(t, req.Method) {
		assert.Equal(t, "GetActiveMessageSessions", req.Method.Name)
		assert.Equal(t, 1, req.Method.Version)
	}
}

func TestIFriendMessagesService_GetRecentMessages(t *testing.T) {
	var ci *steam.IFriendMessagesService
	var err error
	var req *geyser.Request

	client, err := steam.New()

	require.NoError(t, err)
	require.NotNil(t, client)

	ci, err = steam.NewIFriendMessagesService(client)

	require.NoError(t, err)
	require.NotNil(t, ci)

	req, err = ci.GetRecentMessages()

	require.NoError(t, err)
	require.NotNil(t, req)

	assert.Same(t, ci.Interface, req.Interface)

	if assert.NotNil(t, req.Method) {
		assert.Equal(t, "GetRecentMessages", req.Method.Name)
		assert.Equal(t, 1, req.Method.Version)
	}
}

func TestIFriendMessagesService_MarkOfflineMessagesRead(t *testing.T) {
	var ci *steam.IFriendMessagesService
	var err error
	var req *geyser.Request

	client, err := steam.New()

	require.NoError(t, err)
	require.NotNil(t, client)

	ci, err = steam.NewIFriendMessagesService(client)

	require.NoError(t, err)
	require.NotNil(t, ci)

	req, err = ci.MarkOfflineMessagesRead()

	require.NoError(t, err)
	require.NotNil(t, req)

	assert.Same(t, ci.Interface, req.Interface)

	if assert.NotNil(t, req.Method) {
		assert.Equal(t, "MarkOfflineMessagesRead", req.Method.Name)
		assert.Equal(t, 1, req.Method.Version)
	}
}
