// Code generated by geyser. DO NOT EDIT.

package steam_test

import (
	"github.com/13k/geyser/v2"
	"github.com/13k/geyser/v2/steam"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
)

func TestNewIRemoteClientService(t *testing.T) {
	client, err := steam.New()

	require.NoError(t, err)
	require.NotNil(t, client)

	ci, err := steam.NewIRemoteClientService(client)

	require.NoError(t, err)
	require.NotNil(t, ci)

	assert.Same(t, client, ci.Client)
	assert.NotNil(t, ci.Interface)
}

func TestIRemoteClientService_NotifyRegisterStatusUpdate(t *testing.T) {
	var ci *steam.IRemoteClientService
	var err error
	var req *geyser.Request

	client, err := steam.New()

	require.NoError(t, err)
	require.NotNil(t, client)

	ci, err = steam.NewIRemoteClientService(client)

	require.NoError(t, err)
	require.NotNil(t, ci)

	req, err = ci.NotifyRegisterStatusUpdate()

	require.NoError(t, err)
	require.NotNil(t, req)

	assert.Same(t, ci.Interface, req.Interface)

	if assert.NotNil(t, req.Method) {
		assert.Equal(t, "NotifyRegisterStatusUpdate", req.Method.Name)
		assert.Equal(t, 1, req.Method.Version)
	}
}

func TestIRemoteClientService_NotifyRemotePacket(t *testing.T) {
	var ci *steam.IRemoteClientService
	var err error
	var req *geyser.Request

	client, err := steam.New()

	require.NoError(t, err)
	require.NotNil(t, client)

	ci, err = steam.NewIRemoteClientService(client)

	require.NoError(t, err)
	require.NotNil(t, ci)

	req, err = ci.NotifyRemotePacket()

	require.NoError(t, err)
	require.NotNil(t, req)

	assert.Same(t, ci.Interface, req.Interface)

	if assert.NotNil(t, req.Method) {
		assert.Equal(t, "NotifyRemotePacket", req.Method.Name)
		assert.Equal(t, 1, req.Method.Version)
	}
}

func TestIRemoteClientService_NotifyUnregisterStatusUpdate(t *testing.T) {
	var ci *steam.IRemoteClientService
	var err error
	var req *geyser.Request

	client, err := steam.New()

	require.NoError(t, err)
	require.NotNil(t, client)

	ci, err = steam.NewIRemoteClientService(client)

	require.NoError(t, err)
	require.NotNil(t, ci)

	req, err = ci.NotifyUnregisterStatusUpdate()

	require.NoError(t, err)
	require.NotNil(t, req)

	assert.Same(t, ci.Interface, req.Interface)

	if assert.NotNil(t, req.Method) {
		assert.Equal(t, "NotifyUnregisterStatusUpdate", req.Method.Name)
		assert.Equal(t, 1, req.Method.Version)
	}
}
