// Code generated by geyser. DO NOT EDIT.

package steam_test

import (
	"github.com/13k/geyser"
	"github.com/13k/geyser/steam"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
)

func TestNewISteamUser(t *testing.T) {
	client := &steam.Client{}
	iface, err := steam.NewISteamUser(client)

	require.NoError(t, err)
	require.NotNil(t, iface)

	assert.Same(t, client, iface.Client)
	assert.NotNil(t, iface.Interface)
}

func TestISteamUser_GetFriendList(t *testing.T) {
	var iface *steam.ISteamUser
	var err error
	var req *geyser.Request

	client := &steam.Client{}

	iface, err = steam.NewISteamUser(client)

	require.NoError(t, err)
	require.NotNil(t, iface)

	req, err = iface.GetFriendList()

	require.NoError(t, err)
	require.NotNil(t, req)

	assert.Same(t, client, req.Client)
	assert.Same(t, iface.Interface, req.Interface)

	if assert.NotNil(t, req.Method) {
		assert.Equal(t, "GetFriendList", req.Method.Name)
		assert.Equal(t, 1, req.Method.Version)
	}
}

func TestISteamUser_GetPlayerBans(t *testing.T) {
	var iface *steam.ISteamUser
	var err error
	var req *geyser.Request

	client := &steam.Client{}

	iface, err = steam.NewISteamUser(client)

	require.NoError(t, err)
	require.NotNil(t, iface)

	req, err = iface.GetPlayerBans()

	require.NoError(t, err)
	require.NotNil(t, req)

	assert.Same(t, client, req.Client)
	assert.Same(t, iface.Interface, req.Interface)

	if assert.NotNil(t, req.Method) {
		assert.Equal(t, "GetPlayerBans", req.Method.Name)
		assert.Equal(t, 1, req.Method.Version)
	}
}

func TestISteamUser_GetPlayerSummaries(t *testing.T) {
	var iface *steam.ISteamUser
	var err error
	var req *geyser.Request

	client := &steam.Client{}

	iface, err = steam.NewISteamUser(client)

	require.NoError(t, err)
	require.NotNil(t, iface)

	req, err = iface.GetPlayerSummaries(1)

	require.NoError(t, err)
	require.NotNil(t, req)

	assert.Same(t, client, req.Client)
	assert.Same(t, iface.Interface, req.Interface)

	if assert.NotNil(t, req.Method) {
		assert.Equal(t, "GetPlayerSummaries", req.Method.Name)
		assert.Equal(t, 1, req.Method.Version)
	}

	iface, err = steam.NewISteamUser(client)

	require.NoError(t, err)
	require.NotNil(t, iface)

	req, err = iface.GetPlayerSummaries(2)

	require.NoError(t, err)
	require.NotNil(t, req)

	assert.Same(t, client, req.Client)
	assert.Same(t, iface.Interface, req.Interface)

	if assert.NotNil(t, req.Method) {
		assert.Equal(t, "GetPlayerSummaries", req.Method.Name)
		assert.Equal(t, 2, req.Method.Version)
	}
}

func TestISteamUser_GetUserGroupList(t *testing.T) {
	var iface *steam.ISteamUser
	var err error
	var req *geyser.Request

	client := &steam.Client{}

	iface, err = steam.NewISteamUser(client)

	require.NoError(t, err)
	require.NotNil(t, iface)

	req, err = iface.GetUserGroupList()

	require.NoError(t, err)
	require.NotNil(t, req)

	assert.Same(t, client, req.Client)
	assert.Same(t, iface.Interface, req.Interface)

	if assert.NotNil(t, req.Method) {
		assert.Equal(t, "GetUserGroupList", req.Method.Name)
		assert.Equal(t, 1, req.Method.Version)
	}
}

func TestISteamUser_ResolveVanityURL(t *testing.T) {
	var iface *steam.ISteamUser
	var err error
	var req *geyser.Request

	client := &steam.Client{}

	iface, err = steam.NewISteamUser(client)

	require.NoError(t, err)
	require.NotNil(t, iface)

	req, err = iface.ResolveVanityURL()

	require.NoError(t, err)
	require.NotNil(t, req)

	assert.Same(t, client, req.Client)
	assert.Same(t, iface.Interface, req.Interface)

	if assert.NotNil(t, req.Method) {
		assert.Equal(t, "ResolveVanityURL", req.Method.Name)
		assert.Equal(t, 1, req.Method.Version)
	}
}
