// Code generated by geyser. DO NOT EDIT.

package steam_test

import (
	"github.com/13k/geyser"
	"github.com/13k/geyser/steam"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
)

func TestNewISteamCDN(t *testing.T) {
	client, err := steam.New()

	require.NoError(t, err)
	require.NotNil(t, client)

	ci, err := steam.NewISteamCDN(client)

	require.NoError(t, err)
	require.NotNil(t, ci)

	assert.Same(t, client, ci.Client)
	assert.NotNil(t, ci.Interface)
}

func TestISteamCDN_SetClientFilters(t *testing.T) {
	var ci *steam.ISteamCDN
	var err error
	var req *geyser.Request

	client, err := steam.New()

	require.NoError(t, err)
	require.NotNil(t, client)

	ci, err = steam.NewISteamCDN(client)

	require.NoError(t, err)
	require.NotNil(t, ci)

	req, err = ci.SetClientFilters()

	require.NoError(t, err)
	require.NotNil(t, req)

	assert.Same(t, ci.Interface, req.Interface)

	if assert.NotNil(t, req.Method) {
		assert.Equal(t, "SetClientFilters", req.Method.Name)
		assert.Equal(t, 1, req.Method.Version)
	}
}

func TestISteamCDN_SetPerformanceStats(t *testing.T) {
	var ci *steam.ISteamCDN
	var err error
	var req *geyser.Request

	client, err := steam.New()

	require.NoError(t, err)
	require.NotNil(t, client)

	ci, err = steam.NewISteamCDN(client)

	require.NoError(t, err)
	require.NotNil(t, ci)

	req, err = ci.SetPerformanceStats()

	require.NoError(t, err)
	require.NotNil(t, req)

	assert.Same(t, ci.Interface, req.Interface)

	if assert.NotNil(t, req.Method) {
		assert.Equal(t, "SetPerformanceStats", req.Method.Name)
		assert.Equal(t, 1, req.Method.Version)
	}
}
