// Code generated by geyser. DO NOT EDIT.
// API interface: ISteamTVService.

package steam

import (
	"github.com/13k/geyser/v2"
	"github.com/13k/geyser/v2/schema"
	"net/http"
)

// SchemaISteamTVService stores the Interfaces for interface ISteamTVService.
var SchemaISteamTVService = schema.MustNewInterfaces(
	&schema.Interface{
		Methods: schema.MustNewMethods(
			&schema.Method{
				HTTPMethod:   http.MethodGet,
				Name:         "CreateBroadcastChannel",
				Params:       schema.NewMethodParams(),
				Undocumented: true,
				Version:      1,
			},
			&schema.Method{
				HTTPMethod:   http.MethodGet,
				Name:         "GetBroadcastChannelID",
				Params:       schema.NewMethodParams(),
				Undocumented: true,
				Version:      1,
			},
			&schema.Method{
				HTTPMethod:   http.MethodGet,
				Name:         "SetBroadcastChannelProfile",
				Params:       schema.NewMethodParams(),
				Undocumented: true,
				Version:      1,
			},
			&schema.Method{
				HTTPMethod:   http.MethodGet,
				Name:         "GetBroadcastChannelProfile",
				Params:       schema.NewMethodParams(),
				Undocumented: true,
				Version:      1,
			},
			&schema.Method{
				HTTPMethod:   http.MethodGet,
				Name:         "SetBroadcastChannelImage",
				Params:       schema.NewMethodParams(),
				Undocumented: true,
				Version:      1,
			},
			&schema.Method{
				HTTPMethod:   http.MethodGet,
				Name:         "GetBroadcastChannelImages",
				Params:       schema.NewMethodParams(),
				Undocumented: true,
				Version:      1,
			},
			&schema.Method{
				HTTPMethod:   http.MethodGet,
				Name:         "SetBroadcastChannelLinkRegions",
				Params:       schema.NewMethodParams(),
				Undocumented: true,
				Version:      1,
			},
			&schema.Method{
				HTTPMethod:   http.MethodGet,
				Name:         "GetBroadcastChannelLinks",
				Params:       schema.NewMethodParams(),
				Undocumented: true,
				Version:      1,
			},
			&schema.Method{
				HTTPMethod:   http.MethodGet,
				Name:         "GetBroadcastChannelBroadcasters",
				Params:       schema.NewMethodParams(),
				Undocumented: true,
				Version:      1,
			},
			&schema.Method{
				HTTPMethod:   http.MethodGet,
				Name:         "GetFollowedChannels",
				Params:       schema.NewMethodParams(),
				Undocumented: true,
				Version:      1,
			},
			&schema.Method{
				HTTPMethod:   http.MethodGet,
				Name:         "GetSubscribedChannels",
				Params:       schema.NewMethodParams(),
				Undocumented: true,
				Version:      1,
			},
			&schema.Method{
				HTTPMethod:   http.MethodGet,
				Name:         "GetBroadcastChannelStatus",
				Params:       schema.NewMethodParams(),
				Undocumented: true,
				Version:      1,
			},
			&schema.Method{
				HTTPMethod:   http.MethodGet,
				Name:         "FollowBroadcastChannel",
				Params:       schema.NewMethodParams(),
				Undocumented: true,
				Version:      1,
			},
			&schema.Method{
				HTTPMethod:   http.MethodGet,
				Name:         "SubscribeBroadcastChannel",
				Params:       schema.NewMethodParams(),
				Undocumented: true,
				Version:      1,
			},
			&schema.Method{
				HTTPMethod:   http.MethodGet,
				Name:         "ReportBroadcastChannel",
				Params:       schema.NewMethodParams(),
				Undocumented: true,
				Version:      1,
			},
			&schema.Method{
				HTTPMethod:   http.MethodGet,
				Name:         "GetBroadcastChannelInteraction",
				Params:       schema.NewMethodParams(),
				Undocumented: true,
				Version:      1,
			},
			&schema.Method{
				HTTPMethod:   http.MethodGet,
				Name:         "GetGames",
				Params:       schema.NewMethodParams(),
				Undocumented: true,
				Version:      1,
			},
			&schema.Method{
				HTTPMethod:   http.MethodGet,
				Name:         "GetFeatured",
				Params:       schema.NewMethodParams(),
				Undocumented: true,
				Version:      1,
			},
			&schema.Method{
				HTTPMethod:   http.MethodGet,
				Name:         "AddChatBan",
				Params:       schema.NewMethodParams(),
				Undocumented: true,
				Version:      1,
			},
			&schema.Method{
				HTTPMethod:   http.MethodGet,
				Name:         "GetChatBans",
				Params:       schema.NewMethodParams(),
				Undocumented: true,
				Version:      1,
			},
			&schema.Method{
				HTTPMethod:   http.MethodGet,
				Name:         "AddChatModerator",
				Params:       schema.NewMethodParams(),
				Undocumented: true,
				Version:      1,
			},
			&schema.Method{
				HTTPMethod:   http.MethodGet,
				Name:         "GetChatModerators",
				Params:       schema.NewMethodParams(),
				Undocumented: true,
				Version:      1,
			},
			&schema.Method{
				HTTPMethod:   http.MethodGet,
				Name:         "AddWordBan",
				Params:       schema.NewMethodParams(),
				Undocumented: true,
				Version:      1,
			},
			&schema.Method{
				HTTPMethod:   http.MethodGet,
				Name:         "GetWordBans",
				Params:       schema.NewMethodParams(),
				Undocumented: true,
				Version:      1,
			},
			&schema.Method{
				HTTPMethod:   http.MethodGet,
				Name:         "JoinChat",
				Params:       schema.NewMethodParams(),
				Undocumented: true,
				Version:      1,
			},
			&schema.Method{
				HTTPMethod:   http.MethodGet,
				Name:         "Search",
				Params:       schema.NewMethodParams(),
				Undocumented: true,
				Version:      1,
			},
			&schema.Method{
				HTTPMethod:   http.MethodGet,
				Name:         "GetSteamTVUserSettings",
				Params:       schema.NewMethodParams(),
				Undocumented: true,
				Version:      1,
			},
			&schema.Method{
				HTTPMethod:   http.MethodGet,
				Name:         "SetSteamTVUserSettings",
				Params:       schema.NewMethodParams(),
				Undocumented: true,
				Version:      1,
			},
			&schema.Method{
				HTTPMethod:   http.MethodGet,
				Name:         "GetMyBroadcastChannels",
				Params:       schema.NewMethodParams(),
				Undocumented: true,
				Version:      1,
			},
			&schema.Method{
				HTTPMethod:   http.MethodGet,
				Name:         "GetBroadcastChannelClips",
				Params:       schema.NewMethodParams(),
				Undocumented: true,
				Version:      1,
			},
			&schema.Method{
				HTTPMethod:   http.MethodGet,
				Name:         "GetChannels",
				Params:       schema.NewMethodParams(),
				Undocumented: true,
				Version:      1,
			},
			&schema.Method{
				HTTPMethod:   http.MethodGet,
				Name:         "GetHomePageContents",
				Params:       schema.NewMethodParams(),
				Undocumented: true,
				Version:      1,
			},
		),
		Name:         "ISteamTVService",
		Undocumented: true,
	},
)

// ISteamTVService represents interface ISteamTVService.
//
// This is an undocumented interface.
type ISteamTVService struct {
	Client    *Client
	Interface *schema.Interface
}

// NewISteamTVService creates a new ISteamTVService interface.
func NewISteamTVService(c *Client) (*ISteamTVService, error) {
	si, err := SchemaISteamTVService.Get(schema.InterfaceKey{Name: "ISteamTVService"})

	if err != nil {
		return nil, err
	}

	s := &ISteamTVService{
		Client:    c,
		Interface: si,
	}

	return s, nil
}

// ISteamTVService creates a new ISteamTVService interface.
func (c *Client) ISteamTVService() (*ISteamTVService, error) {
	return NewISteamTVService(c)
}

/*
AddChatBan creates a Request for interface method AddChatBan.

This is an undocumented method.
*/
func (i *ISteamTVService) AddChatBan() (*geyser.Request, error) {
	sm, err := i.Interface.Methods.Get(schema.MethodKey{
		Name:    "AddChatBan",
		Version: 1,
	})

	if err != nil {
		return nil, err
	}

	req := geyser.NewRequest(i.Interface, sm)

	return req, nil
}

/*
AddChatModerator creates a Request for interface method AddChatModerator.

This is an undocumented method.
*/
func (i *ISteamTVService) AddChatModerator() (*geyser.Request, error) {
	sm, err := i.Interface.Methods.Get(schema.MethodKey{
		Name:    "AddChatModerator",
		Version: 1,
	})

	if err != nil {
		return nil, err
	}

	req := geyser.NewRequest(i.Interface, sm)

	return req, nil
}

/*
AddWordBan creates a Request for interface method AddWordBan.

This is an undocumented method.
*/
func (i *ISteamTVService) AddWordBan() (*geyser.Request, error) {
	sm, err := i.Interface.Methods.Get(schema.MethodKey{
		Name:    "AddWordBan",
		Version: 1,
	})

	if err != nil {
		return nil, err
	}

	req := geyser.NewRequest(i.Interface, sm)

	return req, nil
}

/*
CreateBroadcastChannel creates a Request for interface method CreateBroadcastChannel.

This is an undocumented method.
*/
func (i *ISteamTVService) CreateBroadcastChannel() (*geyser.Request, error) {
	sm, err := i.Interface.Methods.Get(schema.MethodKey{
		Name:    "CreateBroadcastChannel",
		Version: 1,
	})

	if err != nil {
		return nil, err
	}

	req := geyser.NewRequest(i.Interface, sm)

	return req, nil
}

/*
FollowBroadcastChannel creates a Request for interface method FollowBroadcastChannel.

This is an undocumented method.
*/
func (i *ISteamTVService) FollowBroadcastChannel() (*geyser.Request, error) {
	sm, err := i.Interface.Methods.Get(schema.MethodKey{
		Name:    "FollowBroadcastChannel",
		Version: 1,
	})

	if err != nil {
		return nil, err
	}

	req := geyser.NewRequest(i.Interface, sm)

	return req, nil
}

/*
GetBroadcastChannelBroadcasters creates a Request for interface method GetBroadcastChannelBroadcasters.

This is an undocumented method.
*/
func (i *ISteamTVService) GetBroadcastChannelBroadcasters() (*geyser.Request, error) {
	sm, err := i.Interface.Methods.Get(schema.MethodKey{
		Name:    "GetBroadcastChannelBroadcasters",
		Version: 1,
	})

	if err != nil {
		return nil, err
	}

	req := geyser.NewRequest(i.Interface, sm)

	return req, nil
}

/*
GetBroadcastChannelClips creates a Request for interface method GetBroadcastChannelClips.

This is an undocumented method.
*/
func (i *ISteamTVService) GetBroadcastChannelClips() (*geyser.Request, error) {
	sm, err := i.Interface.Methods.Get(schema.MethodKey{
		Name:    "GetBroadcastChannelClips",
		Version: 1,
	})

	if err != nil {
		return nil, err
	}

	req := geyser.NewRequest(i.Interface, sm)

	return req, nil
}

/*
GetBroadcastChannelID creates a Request for interface method GetBroadcastChannelID.

This is an undocumented method.
*/
func (i *ISteamTVService) GetBroadcastChannelID() (*geyser.Request, error) {
	sm, err := i.Interface.Methods.Get(schema.MethodKey{
		Name:    "GetBroadcastChannelID",
		Version: 1,
	})

	if err != nil {
		return nil, err
	}

	req := geyser.NewRequest(i.Interface, sm)

	return req, nil
}

/*
GetBroadcastChannelImages creates a Request for interface method GetBroadcastChannelImages.

This is an undocumented method.
*/
func (i *ISteamTVService) GetBroadcastChannelImages() (*geyser.Request, error) {
	sm, err := i.Interface.Methods.Get(schema.MethodKey{
		Name:    "GetBroadcastChannelImages",
		Version: 1,
	})

	if err != nil {
		return nil, err
	}

	req := geyser.NewRequest(i.Interface, sm)

	return req, nil
}

/*
GetBroadcastChannelInteraction creates a Request for interface method GetBroadcastChannelInteraction.

This is an undocumented method.
*/
func (i *ISteamTVService) GetBroadcastChannelInteraction() (*geyser.Request, error) {
	sm, err := i.Interface.Methods.Get(schema.MethodKey{
		Name:    "GetBroadcastChannelInteraction",
		Version: 1,
	})

	if err != nil {
		return nil, err
	}

	req := geyser.NewRequest(i.Interface, sm)

	return req, nil
}

/*
GetBroadcastChannelLinks creates a Request for interface method GetBroadcastChannelLinks.

This is an undocumented method.
*/
func (i *ISteamTVService) GetBroadcastChannelLinks() (*geyser.Request, error) {
	sm, err := i.Interface.Methods.Get(schema.MethodKey{
		Name:    "GetBroadcastChannelLinks",
		Version: 1,
	})

	if err != nil {
		return nil, err
	}

	req := geyser.NewRequest(i.Interface, sm)

	return req, nil
}

/*
GetBroadcastChannelProfile creates a Request for interface method GetBroadcastChannelProfile.

This is an undocumented method.
*/
func (i *ISteamTVService) GetBroadcastChannelProfile() (*geyser.Request, error) {
	sm, err := i.Interface.Methods.Get(schema.MethodKey{
		Name:    "GetBroadcastChannelProfile",
		Version: 1,
	})

	if err != nil {
		return nil, err
	}

	req := geyser.NewRequest(i.Interface, sm)

	return req, nil
}

/*
GetBroadcastChannelStatus creates a Request for interface method GetBroadcastChannelStatus.

This is an undocumented method.
*/
func (i *ISteamTVService) GetBroadcastChannelStatus() (*geyser.Request, error) {
	sm, err := i.Interface.Methods.Get(schema.MethodKey{
		Name:    "GetBroadcastChannelStatus",
		Version: 1,
	})

	if err != nil {
		return nil, err
	}

	req := geyser.NewRequest(i.Interface, sm)

	return req, nil
}

/*
GetChannels creates a Request for interface method GetChannels.

This is an undocumented method.
*/
func (i *ISteamTVService) GetChannels() (*geyser.Request, error) {
	sm, err := i.Interface.Methods.Get(schema.MethodKey{
		Name:    "GetChannels",
		Version: 1,
	})

	if err != nil {
		return nil, err
	}

	req := geyser.NewRequest(i.Interface, sm)

	return req, nil
}

/*
GetChatBans creates a Request for interface method GetChatBans.

This is an undocumented method.
*/
func (i *ISteamTVService) GetChatBans() (*geyser.Request, error) {
	sm, err := i.Interface.Methods.Get(schema.MethodKey{
		Name:    "GetChatBans",
		Version: 1,
	})

	if err != nil {
		return nil, err
	}

	req := geyser.NewRequest(i.Interface, sm)

	return req, nil
}

/*
GetChatModerators creates a Request for interface method GetChatModerators.

This is an undocumented method.
*/
func (i *ISteamTVService) GetChatModerators() (*geyser.Request, error) {
	sm, err := i.Interface.Methods.Get(schema.MethodKey{
		Name:    "GetChatModerators",
		Version: 1,
	})

	if err != nil {
		return nil, err
	}

	req := geyser.NewRequest(i.Interface, sm)

	return req, nil
}

/*
GetFeatured creates a Request for interface method GetFeatured.

This is an undocumented method.
*/
func (i *ISteamTVService) GetFeatured() (*geyser.Request, error) {
	sm, err := i.Interface.Methods.Get(schema.MethodKey{
		Name:    "GetFeatured",
		Version: 1,
	})

	if err != nil {
		return nil, err
	}

	req := geyser.NewRequest(i.Interface, sm)

	return req, nil
}

/*
GetFollowedChannels creates a Request for interface method GetFollowedChannels.

This is an undocumented method.
*/
func (i *ISteamTVService) GetFollowedChannels() (*geyser.Request, error) {
	sm, err := i.Interface.Methods.Get(schema.MethodKey{
		Name:    "GetFollowedChannels",
		Version: 1,
	})

	if err != nil {
		return nil, err
	}

	req := geyser.NewRequest(i.Interface, sm)

	return req, nil
}

/*
GetGames creates a Request for interface method GetGames.

This is an undocumented method.
*/
func (i *ISteamTVService) GetGames() (*geyser.Request, error) {
	sm, err := i.Interface.Methods.Get(schema.MethodKey{
		Name:    "GetGames",
		Version: 1,
	})

	if err != nil {
		return nil, err
	}

	req := geyser.NewRequest(i.Interface, sm)

	return req, nil
}

/*
GetHomePageContents creates a Request for interface method GetHomePageContents.

This is an undocumented method.
*/
func (i *ISteamTVService) GetHomePageContents() (*geyser.Request, error) {
	sm, err := i.Interface.Methods.Get(schema.MethodKey{
		Name:    "GetHomePageContents",
		Version: 1,
	})

	if err != nil {
		return nil, err
	}

	req := geyser.NewRequest(i.Interface, sm)

	return req, nil
}

/*
GetMyBroadcastChannels creates a Request for interface method GetMyBroadcastChannels.

This is an undocumented method.
*/
func (i *ISteamTVService) GetMyBroadcastChannels() (*geyser.Request, error) {
	sm, err := i.Interface.Methods.Get(schema.MethodKey{
		Name:    "GetMyBroadcastChannels",
		Version: 1,
	})

	if err != nil {
		return nil, err
	}

	req := geyser.NewRequest(i.Interface, sm)

	return req, nil
}

/*
GetSteamTVUserSettings creates a Request for interface method GetSteamTVUserSettings.

This is an undocumented method.
*/
func (i *ISteamTVService) GetSteamTVUserSettings() (*geyser.Request, error) {
	sm, err := i.Interface.Methods.Get(schema.MethodKey{
		Name:    "GetSteamTVUserSettings",
		Version: 1,
	})

	if err != nil {
		return nil, err
	}

	req := geyser.NewRequest(i.Interface, sm)

	return req, nil
}

/*
GetSubscribedChannels creates a Request for interface method GetSubscribedChannels.

This is an undocumented method.
*/
func (i *ISteamTVService) GetSubscribedChannels() (*geyser.Request, error) {
	sm, err := i.Interface.Methods.Get(schema.MethodKey{
		Name:    "GetSubscribedChannels",
		Version: 1,
	})

	if err != nil {
		return nil, err
	}

	req := geyser.NewRequest(i.Interface, sm)

	return req, nil
}

/*
GetWordBans creates a Request for interface method GetWordBans.

This is an undocumented method.
*/
func (i *ISteamTVService) GetWordBans() (*geyser.Request, error) {
	sm, err := i.Interface.Methods.Get(schema.MethodKey{
		Name:    "GetWordBans",
		Version: 1,
	})

	if err != nil {
		return nil, err
	}

	req := geyser.NewRequest(i.Interface, sm)

	return req, nil
}

/*
JoinChat creates a Request for interface method JoinChat.

This is an undocumented method.
*/
func (i *ISteamTVService) JoinChat() (*geyser.Request, error) {
	sm, err := i.Interface.Methods.Get(schema.MethodKey{
		Name:    "JoinChat",
		Version: 1,
	})

	if err != nil {
		return nil, err
	}

	req := geyser.NewRequest(i.Interface, sm)

	return req, nil
}

/*
ReportBroadcastChannel creates a Request for interface method ReportBroadcastChannel.

This is an undocumented method.
*/
func (i *ISteamTVService) ReportBroadcastChannel() (*geyser.Request, error) {
	sm, err := i.Interface.Methods.Get(schema.MethodKey{
		Name:    "ReportBroadcastChannel",
		Version: 1,
	})

	if err != nil {
		return nil, err
	}

	req := geyser.NewRequest(i.Interface, sm)

	return req, nil
}

/*
Search creates a Request for interface method Search.

This is an undocumented method.
*/
func (i *ISteamTVService) Search() (*geyser.Request, error) {
	sm, err := i.Interface.Methods.Get(schema.MethodKey{
		Name:    "Search",
		Version: 1,
	})

	if err != nil {
		return nil, err
	}

	req := geyser.NewRequest(i.Interface, sm)

	return req, nil
}

/*
SetBroadcastChannelImage creates a Request for interface method SetBroadcastChannelImage.

This is an undocumented method.
*/
func (i *ISteamTVService) SetBroadcastChannelImage() (*geyser.Request, error) {
	sm, err := i.Interface.Methods.Get(schema.MethodKey{
		Name:    "SetBroadcastChannelImage",
		Version: 1,
	})

	if err != nil {
		return nil, err
	}

	req := geyser.NewRequest(i.Interface, sm)

	return req, nil
}

/*
SetBroadcastChannelLinkRegions creates a Request for interface method SetBroadcastChannelLinkRegions.

This is an undocumented method.
*/
func (i *ISteamTVService) SetBroadcastChannelLinkRegions() (*geyser.Request, error) {
	sm, err := i.Interface.Methods.Get(schema.MethodKey{
		Name:    "SetBroadcastChannelLinkRegions",
		Version: 1,
	})

	if err != nil {
		return nil, err
	}

	req := geyser.NewRequest(i.Interface, sm)

	return req, nil
}

/*
SetBroadcastChannelProfile creates a Request for interface method SetBroadcastChannelProfile.

This is an undocumented method.
*/
func (i *ISteamTVService) SetBroadcastChannelProfile() (*geyser.Request, error) {
	sm, err := i.Interface.Methods.Get(schema.MethodKey{
		Name:    "SetBroadcastChannelProfile",
		Version: 1,
	})

	if err != nil {
		return nil, err
	}

	req := geyser.NewRequest(i.Interface, sm)

	return req, nil
}

/*
SetSteamTVUserSettings creates a Request for interface method SetSteamTVUserSettings.

This is an undocumented method.
*/
func (i *ISteamTVService) SetSteamTVUserSettings() (*geyser.Request, error) {
	sm, err := i.Interface.Methods.Get(schema.MethodKey{
		Name:    "SetSteamTVUserSettings",
		Version: 1,
	})

	if err != nil {
		return nil, err
	}

	req := geyser.NewRequest(i.Interface, sm)

	return req, nil
}

/*
SubscribeBroadcastChannel creates a Request for interface method SubscribeBroadcastChannel.

This is an undocumented method.
*/
func (i *ISteamTVService) SubscribeBroadcastChannel() (*geyser.Request, error) {
	sm, err := i.Interface.Methods.Get(schema.MethodKey{
		Name:    "SubscribeBroadcastChannel",
		Version: 1,
	})

	if err != nil {
		return nil, err
	}

	req := geyser.NewRequest(i.Interface, sm)

	return req, nil
}
